codeformaine/apps/brigade/urls.py
from django.conf.urls import include, url
from brigade import views as brigade_views


# custom views
urlpatterns = [
    url(r'^', include('brigade.worker_urls')),
    url(r'^', include('brigade.project_urls')),
    url(r'^', include('brigade.idea_urls')),
    url(r'^events/add/',
        view=brigade_views.EventCreateView.as_view(),
        name="event-create"),

    url(r'^events/(?P<slug>[-\w]+)/',
        view=brigade_views.EventDetailView.as_view(),
        name="event-detail"),

    url(r'^events/$',
        view=brigade_views.EventListView.as_view(),
        name="event-list"),

    url(r'^topic/add/',
        view=brigade_views.TopicCreateView.as_view(),
        name="topic-create"),

    url(r'^topic/(?P<slug>[-\w]+)/',
        view=brigade_views.TopicDetailView.as_view(),
        name="topic-detail"),

    url(r'^topic/$',
        view=brigade_views.TopicListView.as_view(),
        name="topic-list"),

    url(r'^technology/add/',
        view=brigade_views.TechnologyCreateView.as_view(),
        name="technology-create"),

    url(r'^technology/(?P<slug>[-\w]+)/',
        view=brigade_views.TechnologyDetailView.as_view(),
        name="technology-detail"),

    url(r'^technology/$',
        view=brigade_views.TechnologyListView.as_view(),
        name="technology-list"),

    url(r'^$',
        view=brigade_views.DashboardView.as_view(),
        name="dashboard",),
]

codeformaine/urls.py
from cms.sitemaps import CMSSitemap
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^dashboard/', include('brigade.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

codeformaine/apps/brigade/models.py
from django.conf import settings
from django.db import models
from localflavor.us.models import PhoneNumberField
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import (TitleSlugDescriptionModel,
                                         TimeStampedModel)
from django_extensions.db.fields import ShortUUIDField


class Position(TitleSlugDescriptionModel, TimeStampedModel):
    order = models.IntegerField(_('Order'), default=0)

    class Meta:
        ordering = ('order',)

    @models.permalink
    def get_absolute_url(self):
        return ('position-detail', None, {'slug': self.slug})

    def __str__(self):
        return '{0} {1}'.format(self.brigade, self.title)


class Worker(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(_('Name'), max_length=255, blank=True, null=True)
    why = models.TextField(_('Why I am part of Code 4 Maine'), blank=True, null=True)
    website = models.CharField(_('Personal website'), max_length=200, blank=True, null=True)
    phone = models.CharField(_('Phone'), max_length=20, blank=True, null=True)
    city = models.CharField(_('City'), max_length=100, blank=True, null=True)
    skype = models.CharField(_('Skype username'), max_length=100, blank=True, null=True)
    github = models.CharField(_('Github username'), max_length=100, blank=True, null=True)
    twitter = models.CharField(_('Twitter username'), max_length=100, blank=True, null=True)
    facebook = models.CharField(_('Facebook username'), max_length=100, blank=True, null=True)
    instagram = models.CharField(_('Instagram username'), max_length=100, blank=True, null=True)
    linkedin = models.CharField(_('LinkedIn username'), max_length=100, blank=True, null=True)
    email_notify = models.BooleanField(_('Email notifications on updates'), default=True)
    position = models.ForeignKey(Position, blank=True, null=True)
    active = models.BooleanField(_('Is worker active?'), default=True)


    @models.permalink
    def get_absolute_url(self):
        return ('worker-detail', None, {'slug': self.user.username})

    def __str__(self):
        if self.name:
            return '{0}'.format(self.name)
        else:
            return '{0}'.format(self.user)


class BasicItem(TimeStampedModel, TitleSlugDescriptionModel):
    pending = models.BooleanField(default=True)
    project_count = models.IntegerField(default=0)

    class Meta:
        abstract = True

    def __str__(self):
        return '{0}'.format(self.title)

    def save(self, *args, **kwargs):
        super(BasicItem, self).save(*args, **kwargs)

        self.project_count = len(self.project_set.all())

        super(BasicItem, self).save(*args, **kwargs)



class Topic(BasicItem):

    @models.permalink
    def get_absolute_url(self):
        return ('topic-detail', None, {'slug': self.slug})


class Technology(BasicItem):

    @models.permalink
    def get_absolute_url(self):
        return ('technology-detail', None, {'slug': self.slug})


class Event(BasicItem):
    start_date = models.DateField(_('Start date'))
    start_time = models.TimeField(_('Start time'), blank=True, null=True)
    end_date = models.DateField(_('End date'), blank=True, null=True)
    end_time = models.TimeField(_('End time'), blank=True, null=True)
    url = models.CharField(_('Signup URL'), max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    @models.permalink
    def get_absolute_url(self):
        return ('topic-detail', None, {'slug': self.slug})


class HotIdeaManager(models.Manager):
    pass


class ColdIdeaManager(models.Manager):
    pass


class ProjectIdea(TimeStampedModel):
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'))
    slug = ShortUUIDField()
    user_votes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_votes')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True,
            null=True, related_name="project_created_by")
    started_date = models.DateTimeField(blank=True, null=True)

    objects = models.Manager()
    hot_objects = HotIdeaManager()
    cold_objects = ColdIdeaManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return '{0}'.format(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('projectidea-detail', [], {'slug':self.slug})

    @property
    def started(self):
        if not self.started_date:
            return False
        else:
            return True


PROJECT_STATUSES = (('inprogress', 'In Progress'),
                    ('ideation', 'Ideation'),
                    ('stalled', 'Stalled'),
                    ('defunct', 'Defunct'),
                    ('launched', 'Launched'))


class Project(TimeStampedModel, TitleSlugDescriptionModel):
    public_url = models.CharField(max_length=255, blank=True, null=True)
    dev_url = models.CharField(max_length=255, blank=True, null=True)
    git_url = models.CharField(max_length=255, blank=True, null=True)
    topics = models.ManyToManyField(Topic)
    events = models.ManyToManyField(Event)
    technologies = models.ManyToManyField(Technology)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL)
    founder = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
        related_name="founder")
    status = models.CharField(
        max_length=10,
        choices=PROJECT_STATUSES,
        default='ideation')
    color = models.CharField(_('Color'), max_length=100, blank=True, null=True)
    screenshot = models.ImageField(_('Screenshot'), blank=True, null=True,
                                   upload_to='screenshots')
    featured = models.BooleanField(_('Featured'), default=False)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return '{0}'.format(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('project-detail', None, {'slug': self.slug})

    def project_health(self):
        '''
        Project health is determined by a calculus of when things were last
        updated. This includes:

          - number of days since last Buzz
          - number of commits
          - number of unique commiters
          - number of days since last commit
          - stated project status
          - number of stated members
          - number of requests for help
        '''
        return 0


class Link(TimeStampedModel, TitleSlugDescriptionModel):
    project = models.ForeignKey(Project)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    url = models.CharField(max_length=255)

    def __str__(self):
        return '{0} ({1})'.format(self.title, self.url)


class ProjectCommit(TimeStampedModel):
    project = models.ForeignKey(Project)
    chash = models.CharField(max_length=255)
    message = models.TextField(blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    string_author = models.CharField(max_length=255, blank=True, null=True)
    user_author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    diff = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ('project', 'chash')
        ordering = ['-created']

    def __str__(self):
        return 'Commit {0} in {1}'.format(self.chash[:15], self.project)

    @property
    def author(self):
        if self.user_author:
            return self.user_author
        else:
            return self.string_author

    @models.permalink
    def get_absolute_url(self):
        return ('commit-detail', None, {'project_slug': self.project.slug, 'slug': self.chash})


class Buzz(TimeStampedModel, TitleSlugDescriptionModel):
    project = models.ForeignKey(Project)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return '{0}'.format(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('buzz-detail', None, {'project_slug': self.project.slug, 'slug': self.slug})

codeformaine/apps/brigade/forms.py
from django.core.urlresolvers import reverse
import floppyforms.__future__ as forms

from .models import (Project, Topic, Event, Technology, Buzz, Link, ProjectIdea,
                     Worker, Position)

class ProjectIdeaForm(forms.ModelForm):
    class Meta:
        model = ProjectIdea
        exclude = ['user_votes', 'created_by', 'started_date']


class BuzzForm(forms.ModelForm):
    class Meta:
        model = Buzz
        exclude = ['project', 'author']
        readonly = ('links',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ['project', 'author']
        readonly = ('links',)

class ProjectForm(forms.ModelForm):
    topics = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.SelectMultiple(
            attrs={'inline': True, 'class': 'multiselect',}),
        required=False)
    events = forms.ModelMultipleChoiceField(
        queryset=Event.objects.all(),
        widget=forms.SelectMultiple(
            attrs={'inline': True, 'class': 'multiselect',}),
        required=False)
    technologies = forms.ModelMultipleChoiceField(
        queryset=Technology.objects.all(),
        widget=forms.SelectMultiple(
            attrs={'inline': True, 'class': 'multiselect',}),
        required=False)
    color = forms.CharField(
        widget=forms.TextInput(
            attrs={'inline': True, 'class': 'colorpicker',}),
        required=False)

    class Meta:
        model = Project
        fields = ['title', 'description', 'status', 'public_url', 'dev_url',
                  'screenshot', 'git_url', 'topics', 'events',
                  'technologies', 'color']


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        exclude = ['pending', 'project_count']


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        exclude = ['pending', 'project_count']


class TechnologyForm(forms.ModelForm):

    class Meta:
        model = Technology
        exclude = ['pending', 'project_count']


class WorkerForm(forms.ModelForm):
    class Meta:
        model = Worker
        exclude = ['user']

codeformaine/templates/base.html
{% load cms_tags sekizai_tags menu_tags static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="google-site-verification" content="zMwQJxNdc4_Ed6XNGbXgD79uR9pm1VxtI_nd3cS4DYA" />

    <title>{% block title %}Code for Maine{% endblock %}</title>

    <!-- Bootstrap Core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link href="{% static 'css/landing-page.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Josefin+Sans|Droid+Sans|Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    {% render_block "css" %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

  <body {% block body_id %}{% endblock %} class="{% block body_class %}{% endblock %}">
    {% cms_toolbar %}

    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><img src="{% static 'img/cfm_logo_sm.png' %}" /></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
            <li class="dropdown btn btn-default">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-user"></i>&nbsp;&nbsp;{{ request.user.worker_set.all.0 }}</a>
                <ul class="dropdown-menu dropdown-user">
                    <li><a href="{% url 'project-list' %}"><i class="fa fa-line-chart"></i>&nbsp;&nbsp;View Projects</a></li>
                    <li><a href="{% url 'project-create' %}"><i class="fa fa-plus"></i>&nbsp;&nbsp;Add Project</a></li>
                    {% if user.project_set.all %}
                    <li class="divider"></li>
                    <li class="dropdown-header">Your projects</li>
                    {% for project in user.project_set.all %}
                    <li><a href="{{project.get_absolute_url}}">{% if project.color %}<i class="pj-box" style="border-left:15px solid {{project.color}}"></i>{% endif %}&nbsp;&nbsp;{{project}}</a></li>
                    {% endfor %}
                    {% endif %}
                    <li class="divider"></li>
                    <li><a href="{% url 'profile-detail' %}"><i class="fa fa-user fa-fw"></i> Your Profile</a></li>
                    <li><a href="{% url 'account_reset_password' %}"><i class="fa fa-exchange fa-fw"></i> Change Password</a></li>
                    <li class="divider"></li>
                    <li><form id="logout" action="{% url 'account_logout' %}" method="post">{% csrf_token %}</form><a href="#" onclick="javscript:$('#logout').submit()"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
                </ul>
            </li>
            {% else %}
            <li class="">
                <a class="btn btn-default" href="{% url 'account_signup' %}"><i class="fa fa-plus fa-fw"></i> Register a new account</a>
            </li>
            <li>&nbsp;</li>
            <li>
                <a class="btn btn-default" href="{% url 'account_login' %}"><i class="fa fa-sign-in fa-fw"></i> Sign in</a>
            </li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    {% block header %}
    <!-- Header -->
    <div class="intro-header">

        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                        <h2 class="subhead">Come hack for civic good</h2>
                        <h1>Code for Maine</h1>
                        <hr class="intro-divider">
                        <p><i>A <a href="//www.codeforamerica.org">Code for America</a> Brigade</i></p>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <div class="lower-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-9 col-sm-10">
                    <div class="lower-message">
                        <p>Come join developers, designers, data geeks, leaders, and idea-makers who volunteer to help Maine government agencies and civic orgs adopt open web technologies.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-sm-4">
                    <a href="{% url 'account_signup' %}" class="btn btn-primary btn-lg join"><span class="network-name">Join our brigade</span></a>
                </div>
            </div>

        </div>
        <!-- /.container -->
    </div>
    {% endblock header %}

    <!-- Page Content -->
    {% block content %}
    {% endblock content %}

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#home">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                        <a href="{% url 'project-list' %}">Projects</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Code for Maine 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="//code.jquery.com/jquery-2.1.1.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    {% block extra_js %}{% endblock %}
    {% render_block "js" %}

    <!-- Piwik -->
    <script type="text/javascript">
      var _paq = _paq || [];
      _paq.push(['trackPageView']);
      _paq.push(['enableLinkTracking']);
      (function() {
        var u="//stats.codeformaine.org/";
        _paq.push(['setTrackerUrl', u+'piwik.php']);
        _paq.push(['setSiteId', 1]);
        var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
        g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
      })();
    </script>
    <noscript><p><img src="//stats.codeformaine.org/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
    <!-- End Piwik Code -->

</body>

</html>

codeformaine/templates/dashboard_base.html
{% extends "base.html" %}

{% block header %}

    <div class="dashboard-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="dashboard-message">
                        <h2 class="">Brigade Dashboard</h2>
                        <p>Here you can get an eagle-eye view of what's going on in our brigade.</p>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.dashboard-header -->
{% endblock %}

codeformaine/templates/default.html
{% extends "base.html" %}
{% load markdown_deux_tags %}
{% load static %}

{% block full_width %}full_width{% endblock %}

{% block extra_js %}{% endblock %}


{% block content %}
    <div class="content-section-a">

        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">What is Civic Innovation?</h2>
                    <p class="lead"><em>Civic Innovation is a new idea, technology or methodology that challenges and improves upon existing processes and systems, thereby improving the lives of citizens or the function of the society that they live within.</em></p>
                    <p>&mdash; Alex Howard in <a href="http://gov20.govfresh.com/defining-civic-innovation-definition-open-government/">A definition for civic innovation</a></p>
                </div>
                {% with object_list.0 as brigade %}
                <div class="col-lg-7 col-lg-offset-1">
                    <hr class="sectjon-heading-spacer">
                    <div class="clearfix"></div>
                    <h2>Connect With Your Fellow Hackers</h2>
                    <br />
                    <div class="row">
                        <div class="col-lg-3 big-icon">
                            <p class="user"><a href="{% url 'worker-list' %}"><i class="fa fa-user"></i></a></p>
                            <p class="lower"><a href="{% url 'worker-list' %}">Our Brigade</a></p>
                        </div>
                        <div class="col-lg-3 big-icon">
                            <p class="chat"><a href="{% url 'project-list' %}"><i class="fa fa-cubes" style="margin-left:-25px; font-size:9em;"></i></a></p>
                            <p class="lower"><a href="{% url 'project-list' %}">Find a Project</a></p>
                        </div>
                        <div class="col-lg-3 big-icon">
                            <p class="github"><a href="{{brigade.chat}}"><i class="fa fa-comments" style="margin-left:-10px;"></i></a></p>
                            <p class="lower"><a href="{{brigade.chat}}">Chat</a></p>
                        </div>
                </div>
                {% endwith %}
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <div class="container">

            {% if partners or initiatives %}
            <div class="row">
                <h2>Our Initiatives for 2015</h2>
                <hr />
                <div class="col-lg-4">
                    {% with initiatives.0 as object %}
                    <h3><em>{{object.area}} Initiative</em></h3>
                    <h2 class="section-heading">{{object.title}}</h2>
                    <p>{{object.description|truncatewords:"20"}} </p>
                    <p><a href="{{object.get_absolute_url}}">Learn more</a></p>
                    {% endwith %}
                </div>
                <div class="col-lg-4">
                    <img class="img-responsive" src="{% static 'img/bangor-flag.gif' %}" style="border:1px solid #aaa;" alt="">
                </div>
                <div class="col-lg-4 ">
                    {% with partners.0 as object %}
                    <h3><em>{{object.partner_type}} Partner</em></h3>
                    <h2 class="section-heading">{{object.title}}</h2>
                    <p>{{object.description|truncatewords:"20"}} </p>
                    <p><a href="{{object.get_absolute_url}}">Learn more</a></p>
                    {% endwith %}
                </div>
            </div>
            {% endif %}

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-c">

        <div class="container">

            <div class="row">
                <h2>What's going on at Code for Maine?</h2>
                <div class="col-lg-4">
                    <h3 class="section-heading"><i class="fa fa-bullhorn"></i>&nbsp;&nbsp;Project Updates</h3>
                        <ul class="timeline">
                            {% for update in updates %}
                            <li class="well update {% cycle 'timeline-inverted' '' %}" {% if forloop.counter > 2 %}style="display:none;"{% endif %}>
                            <div class="timeline-badge{% if update.summary %} primary"><i class="fa fa-git"></i>{% else %} success"><i class="fa fa-bullhorn">{% endif %}</i>
                                </div>
                                <div class="timeline-panel">
                                    <div class="timeline-heading">
                                        <h4 class="timeline-title"><a href="{{update.get_absolute_url}}">{% if update.title %}{{update.title}}{% endif %}{% if update.summary%}{{update.summary}}{% endif %}</a>
                                        <span class="badge right" style="background-color:{{update.project.color}};"><a href="{{update.project.get_absolute_url}}">{{update.project}}</a></span></h4>
                                        <hr />
                                    </div>
                                    <div class="timeline-body">
                                        {% if update.description %}{{update.description|markdown}}{% endif %}
                                        {% if update.message%}{{update.message}}{% endif %}
                                        <hr />
                                        <p class="byline">{{update.created}} by {% if update.author.username %}<a href="{% url 'worker-detail' update.author.username %}">{% endif %}{{update.author}}{% if update.author.username %}</a>{% endif %}</p>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ul>
                        <p><a class="btn btn-default" href="/dashboard/">See more updates</a></p>
                </div>
                <div class="col-lg-4">
                    <h3 class="section-heading"><i class="fa fa-calendar"></i>&nbsp;&nbsp;Upcoming events</h3>
                    <div class="well event-box">
                        <h4>Next meetup: December 12 @ 6 p.m.</h4>
                        <p>Come join us for our monthly meetup and hack session.</p>
                        <p>Come join us for our monthly meetup and hack session.</p>
                        <p><a class="btn btn-primary" href="http://www.meetup.com/Code-for-Maine/">RSVP @ Meetup.com &raquo;</a></p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <h3 class="section-heading"><i class="fa fa-building"></i>&nbsp;&nbsp;Municipal ME Blog</h3>
                    {% for post in posts %}
                    <div class="well ">
                        <h4>{{ post.title }}
                        <h5><em>{{post.published|date:"M d, Y"}}</em></h5>
                        <p>{{post.content_html|safe|truncatewords:"30"}}
                        <p><a href="{{post.get_absolute_url}}">Continue reading &raquo;</a></p>
                    </div>
                    {% endfor%}
                    <p><a class="btn btn-default" href="">Read more blog posts</a></p>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="banner">

        <div class="container">

            <div class="row">
                <div class="col-lg-6">
                    <h2>Connect with Code for Maine:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/Code4Maine" class="btn btn-default btn-lg"><i class="fa fa-twitter"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/code4maine/" class="btn btn-default btn-lg"><i class="fa fa-github"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="https://codeformaine.org/dashboard/" class="btn btn-default btn-lg"><i class="fa fa-checklist "></i> <span class="network-name">Dashboard</span></a>
                        </li>
                    </ul>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
{% endblock %}