codeformaine/apps/brigade/urls.py
from django.conf.urls import include, url
from brigade import views as brigade_views


# custom views
urlpatterns = [
    url(r'^', include('brigade.worker_urls')),
    url(r'^', include('brigade.project_urls')),
    url(r'^', include('brigade.idea_urls')),
    url(r'^events/add/',
        view=brigade_views.EventCreateView.as_view(),
        name="event-create"),

    url(r'^events/(?P<slug>[-\w]+)/',
        view=brigade_views.EventDetailView.as_view(),
        name="event-detail"),

    url(r'^events/$',
        view=brigade_views.EventListView.as_view(),
        name="event-list"),

    url(r'^topic/add/',
        view=brigade_views.TopicCreateView.as_view(),
        name="topic-create"),

    url(r'^topic/(?P<slug>[-\w]+)/',
        view=brigade_views.TopicDetailView.as_view(),
        name="topic-detail"),

    url(r'^topic/$',
        view=brigade_views.TopicListView.as_view(),
        name="topic-list"),

    url(r'^technology/add/',
        view=brigade_views.TechnologyCreateView.as_view(),
        name="technology-create"),

    url(r'^technology/(?P<slug>[-\w]+)/',
        view=brigade_views.TechnologyDetailView.as_view(),
        name="technology-detail"),

    url(r'^technology/$',
        view=brigade_views.TechnologyListView.as_view(),
        name="technology-list"),

    url(r'^$',
        view=brigade_views.DashboardView.as_view(),
        name="dashboard",),
]

codeformaine/urls.py
from cms.sitemaps import CMSSitemap
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls import include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^robots.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^avatar/', include('avatar.urls')),
    url(r'^dashboard/', include('brigade.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^', include('cms.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

codeformaine/apps/brigade/models.py
from django.conf import settings
from django.db import models
from localflavor.us.models import PhoneNumberField
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import (TitleSlugDescriptionModel,
                                         TimeStampedModel)
from django_extensions.db.fields import ShortUUIDField


class Position(TitleSlugDescriptionModel, TimeStampedModel):
    order = models.IntegerField(_('Order'), default=0)

    class Meta:
        ordering = ('order',)

    @models.permalink
    def get_absolute_url(self):
        return ('position-detail', None, {'slug': self.slug})

    def __str__(self):
        return '{0} {1}'.format(self.brigade, self.title)


class Worker(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(_('Name'), max_length=255, blank=True, null=True)
    why = models.TextField(_('Why I am part of Code 4 Maine'), blank=True, null=True)
    website = models.CharField(_('Personal website'), max_length=200, blank=True, null=True)
    phone = models.CharField(_('Phone'), max_length=20, blank=True, null=True)
    city = models.CharField(_('City'), max_length=100, blank=True, null=True)
    skype = models.CharField(_('Skype username'), max_length=100, blank=True, null=True)
    github = models.CharField(_('Github username'), max_length=100, blank=True, null=True)
    twitter = models.CharField(_('Twitter username'), max_length=100, blank=True, null=True)
    facebook = models.CharField(_('Facebook username'), max_length=100, blank=True, null=True)
    instagram = models.CharField(_('Instagram username'), max_length=100, blank=True, null=True)
    linkedin = models.CharField(_('LinkedIn username'), max_length=100, blank=True, null=True)
    email_notify = models.BooleanField(_('Email notifications on updates'), default=True)
    position = models.ForeignKey(Position, blank=True, null=True)
    active = models.BooleanField(_('Is worker active?'), default=True)


    @models.permalink
    def get_absolute_url(self):
        return ('worker-detail', None, {'slug': self.user.username})

    def __str__(self):
        if self.name:
            return '{0}'.format(self.name)
        else:
            return '{0}'.format(self.user)


class BasicItem(TimeStampedModel, TitleSlugDescriptionModel):
    pending = models.BooleanField(default=True)
    project_count = models.IntegerField(default=0)

    class Meta:
        abstract = True

    def __str__(self):
        return '{0}'.format(self.title)

    def save(self, *args, **kwargs):
        super(BasicItem, self).save(*args, **kwargs)

        self.project_count = len(self.project_set.all())

        super(BasicItem, self).save(*args, **kwargs)



class Topic(BasicItem):

    @models.permalink
    def get_absolute_url(self):
        return ('topic-detail', None, {'slug': self.slug})


class Technology(BasicItem):

    @models.permalink
    def get_absolute_url(self):
        return ('technology-detail', None, {'slug': self.slug})


class Event(BasicItem):
    start_date = models.DateField(_('Start date'))
    start_time = models.TimeField(_('Start time'), blank=True, null=True)
    end_date = models.DateField(_('End date'), blank=True, null=True)
    end_time = models.TimeField(_('End time'), blank=True, null=True)
    url = models.CharField(_('Signup URL'), max_length=255, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)

    @models.permalink
    def get_absolute_url(self):
        return ('topic-detail', None, {'slug': self.slug})


class HotIdeaManager(models.Manager):
    pass


class ColdIdeaManager(models.Manager):
    pass


class ProjectIdea(TimeStampedModel):
    title = models.CharField(_('Title'), max_length=255)
    description = models.TextField(_('Description'))
    slug = ShortUUIDField()
    user_votes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='user_votes')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True,
            null=True, related_name="project_created_by")
    started_date = models.DateTimeField(blank=True, null=True)

    objects = models.Manager()
    hot_objects = HotIdeaManager()
    cold_objects = ColdIdeaManager()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return '{0}'.format(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('projectidea-detail', [], {'slug':self.slug})

    @property
    def started(self):
        if not self.started_date:
            return False
        else:
            return True


PROJECT_STATUSES = (('inprogress', 'In Progress'),
                    ('ideation', 'Ideation'),
                    ('stalled', 'Stalled'),
                    ('defunct', 'Defunct'),
                    ('launched', 'Launched'))


class Project(TimeStampedModel, TitleSlugDescriptionModel):
    public_url = models.CharField(max_length=255, blank=True, null=True)
    dev_url = models.CharField(max_length=255, blank=True, null=True)
    git_url = models.CharField(max_length=255, blank=True, null=True)
    topics = models.ManyToManyField(Topic)
    events = models.ManyToManyField(Event)
    technologies = models.ManyToManyField(Technology)
    members = models.ManyToManyField(settings.AUTH_USER_MODEL)
    founder = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True,
        related_name="founder")
    status = models.CharField(
        max_length=10,
        choices=PROJECT_STATUSES,
        default='ideation')
    color = models.CharField(_('Color'), max_length=100, blank=True, null=True)
    screenshot = models.ImageField(_('Screenshot'), blank=True, null=True,
                                   upload_to='screenshots')
    featured = models.BooleanField(_('Featured'), default=False)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return '{0}'.format(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('project-detail', None, {'slug': self.slug})

    def project_health(self):
        '''
        Project health is determined by a calculus of when things were last
        updated. This includes:

          - number of days since last Buzz
          - number of commits
          - number of unique commiters
          - number of days since last commit
          - stated project status
          - number of stated members
          - number of requests for help
        '''
        return 0


class Link(TimeStampedModel, TitleSlugDescriptionModel):
    project = models.ForeignKey(Project)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    url = models.CharField(max_length=255)

    def __str__(self):
        return '{0} ({1})'.format(self.title, self.url)


class ProjectCommit(TimeStampedModel):
    project = models.ForeignKey(Project)
    chash = models.CharField(max_length=255)
    message = models.TextField(blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    string_author = models.CharField(max_length=255, blank=True, null=True)
    user_author = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    diff = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ('project', 'chash')
        ordering = ['-created']

    def __str__(self):
        return 'Commit {0} in {1}'.format(self.chash[:15], self.project)

    @property
    def author(self):
        if self.user_author:
            return self.user_author
        else:
            return self.string_author

    @models.permalink
    def get_absolute_url(self):
        return ('commit-detail', None, {'project_slug': self.project.slug, 'slug': self.chash})


class Buzz(TimeStampedModel, TitleSlugDescriptionModel):
    project = models.ForeignKey(Project)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)

    def __str__(self):
        return '{0}'.format(self.title)

    @models.permalink
    def get_absolute_url(self):
        return ('buzz-detail', None, {'project_slug': self.project.slug, 'slug': self.slug})

codeformaine/apps/brigade/forms.py
from django.core.urlresolvers import reverse
import floppyforms.__future__ as forms

from .models import (Project, Topic, Event, Technology, Buzz, Link, ProjectIdea,
                     Worker, Position)

class ProjectIdeaForm(forms.ModelForm):
    class Meta:
        model = ProjectIdea
        exclude = ['user_votes', 'created_by', 'started_date']


class BuzzForm(forms.ModelForm):
    class Meta:
        model = Buzz
        exclude = ['project', 'author']
        readonly = ('links',)

class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        exclude = ['project', 'author']
        readonly = ('links',)

class ProjectForm(forms.ModelForm):
    topics = forms.ModelMultipleChoiceField(
        queryset=Topic.objects.all(),
        widget=forms.SelectMultiple(
            attrs={'inline': True, 'class': 'multiselect',}),
        required=False)
    events = forms.ModelMultipleChoiceField(
        queryset=Event.objects.all(),
        widget=forms.SelectMultiple(
            attrs={'inline': True, 'class': 'multiselect',}),
        required=False)
    technologies = forms.ModelMultipleChoiceField(
        queryset=Technology.objects.all(),
        widget=forms.SelectMultiple(
            attrs={'inline': True, 'class': 'multiselect',}),
        required=False)
    color = forms.CharField(
        widget=forms.TextInput(
            attrs={'inline': True, 'class': 'colorpicker',}),
        required=False)

    class Meta:
        model = Project
        fields = ['title', 'description', 'status', 'public_url', 'dev_url',
                  'screenshot', 'git_url', 'topics', 'events',
                  'technologies', 'color']


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        exclude = ['pending', 'project_count']


class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        exclude = ['pending', 'project_count']


class TechnologyForm(forms.ModelForm):

    class Meta:
        model = Technology
        exclude = ['pending', 'project_count']


class WorkerForm(forms.ModelForm):
    class Meta:
        model = Worker
        exclude = ['user']

codeformaine/apps/brigade/templates/brigade/_member_list.html
{% load avatar_tags %}
<div class="member-thumbs row">
{% for member in members %}
    <div class="th" ><a href="{% url 'worker-detail' member.username %}">{% avatar member 65 %}</a></div>
{% endfor %}
</div>

codeformaine/apps/brigade/templates/brigade/buzz_detail.html
{% extends "dashboard_base.html" %}
{% load avatar_tags %}
{% load markdown_deux_tags %}

{% block header_title %}Buzzing About {{object.project}}{% endblock %}

{% block content %}
<div class="content-main">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3>A buzzing</h3>
                <h2>{{object}} </h2>
                <span class="badge" style="background-color:{{object.project.color}};"><a href="{{object.project.get_absolute_url}}">{{object.project}}</a></span>
                {{object.description|markdown}}
                <hr />
                <p class="byline">{{buzz.modified}} by <a href="{% url 'worker-detail' buzz.author.username %}">{{buzz.author}}</a></p>
            </div>
        </div>
        <p><a class="btn btn-default" href="{{buzz.project.get_absolute_url}}">Back to {{buzz.project}}</a></p>
    </div>
</div>
{% endblock %}

codeformaine/apps/brigade/templates/brigade/buzz_form.html
{% extends "modal_base.html" %}
{% load static %}
{% load bootstrap3 %}


{% block content %}

<h2>Let's buzz about {{project}}!</h2>
<form class="short-form" method="post" action="{% url 'buzz-create' project.slug %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <p><input class="btn btn-success" type="submit" value="Post it!"> <button type="button" class="btn btn-danger" value="cancel">Cancel</button></p>
</form>

{% endblock %}

codeformaine/apps/brigade/templates/brigade/dashboard.html
{% extends "dashboard_base.html" %}
{% load avatar_tags %}
{% load markdown_deux_tags %}
{% load static %}

{% block header_title %}Brigade Directory{% endblock %}

{% block extra_js %}
<!-- isotope for the box layout | added for the project_list template -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/2.0.0/isotope.pkgd.min.js"></script>

<script>
var $container = $('#project-container');
// init
$container.isotope({
  // options
  itemSelector: '.item',
  layoutMode: 'fitRows'
});
</script>
{% endblock %}

{% block content %}
<div class="content-main">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="row">
		<h2>Featured Project</h2>
		</div>
	    </div>
            <div class="col-md-12">
                <div class="row">
                    {% for update in updates %}
                    {% if forloop.counter <= 1 %}
                    <div class="col-md-8">
                          <div class="well widget update {% cycle 'timeline-inverted' '' %}">
                            <h4>Recent Activity</h4>
                              <div class="timeline-badge{% if update.summary %} primary"><i class="fa fa-git"></i>{% else %} success"><i class="fa fa-bullhorn"></i>{% endif %}
                                  <span class="timeline-title"><a href="{{update.get_absolute_url}}">{% if update.title %}{{update.title}}{% endif %}{% if update.summary%}{{update.summary}}{% endif %}</a></span>
                                  <div class="timeline-description">
                                      {% if update.summary %}{{ update.summary|truncatewords:"20" }}{% endif %}
                                      {% if update.description %}{{ update.description|truncatewords:"20"  }}{% endif %}
                                  </div>
                                  <span><a class="btn btn-default" href="{{update.project.get_absolute_url}}">Project page</a></span>
                              </div>
                          </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <div class="col-md-4">
                        <div class="well widget help-projects">
                            <h4>Projects that need your help</h4>
                            <p>{{ projects.count }}</p>
                            <span><a class="btn btn-default" href="{% url 'project-list' %}">View projects that need your help</a></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="well widget techs">
                            <h4>Technologies in use</h4>
                            <p>{{ technologies.count }}</p>
                            <span><a class="btn btn-default" href="{% url 'technology-list' %}">View technologies</a></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="well widget commits">
                            <h4>Commits in the past {{commit_days}} days</h4>
                            <p>{{ commits.count }}</p>
                            <span><a class="btn btn-default" href="{% url 'technology-list' %}">View technologies</a></span>
                        </div>
                    </div>
                    <div class="col-md-4 thirds">
                        <div class="well widget projects">
                            <h4>Healthy projects</h4>
                            <p>{{ projects.count }}</p>
                            <span><a class="btn btn-default" href="{% url 'project-list' %}">View projects</a></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="well widget topics">
                            <h4>Topics being covered</h4>
                            <p>{{ topics.count }}</p>
                            <span><a class="btn btn-default" href="{% url 'topic-list' %}">View topics</a></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="well widget workers">
                            <h4>Active Hackers</h4>
                            <p>{{ workers.count }}</p>
                            <span><a class="btn btn-default" href="{% url 'worker-list' %}">View workers</a></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

codeformaine/apps/brigade/templates/brigade/event_form.html
{% extends "modal_base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block content %}

<h2>{% if not object %}Add an Event{% else %}Edit {{object}}{% endif %}</h2>

<form class="modal-form" method="post" action="{% url 'event-create' %}">{% csrf_token %}
    {% bootstrap_form form %}
    <p><input type="submit" class="btn btn-success" value="Add"></p>
</form>

{% endblock %}

codeformaine/apps/brigade/templates/brigade/project_detail.html
{% extends "dashboard_base.html" %}
{% load static %}
{% load markdown_deux_tags %}

{% block extra_js %}
<script src="{% static 'js/eldarion-ajax.min.js' %}"></script>
<script>
$('#modal').on('hidden.bs.modal', function () {
 location.reload();
})
</script>
{% endblock %}

{% block header_title %}Project Directory{% endblock %}

{% block content %}
<div class="content-main">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>{{object}}</h1>
                {% if project.technologies.all %}
                <p>Built with {% for tech in project.technologies.all %}<a class="badge" href="{{tech.get_absolute_url}}">{{tech}}</a> {% endfor %}</p>
                {% endif %}
                        
                <div class="well">
                    <h4>README</h4>
                    {{project.description|markdown}}
                </div>
                <hr />
                <h4>Resources & Links</h4>
                {% for link in project.link_set.all %}
                <p><a href="{{link.url}}">{{link.title}}</a> <i class="small-link">{{link.url}}</i></p>
                {% endfor %}
                {% if user.is_authenticated %}{% if user in project.members.all %}<a href="{% url 'link-create' object.slug %}" class="btn btn-primary" class="" data-toggle="modal" data-target="#modal" >Add a link</a>{% endif %}{% endif %}
                <hr />
                <p class="links">{% if project.public_url %}<a target="_blank" href="{{project.public_url}}"><i class="fa fa-globe"></i></a>{% endif %}{% if project.git_url %} <a target="_blank" href="{{project.github_url}}"><i class="fa fa-github"></i></a>{% endif %}</p>
                <hr />
                <p><i>Founded on {{project.created|date:"r"}} by {{project.founder.username}}</i></p>
            </div>
                
            <div class="col-md-4 columns members">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 style="display:inline; margin-bottom:80px;">Members</h5>
                        {% if request.user.is_authenticated %}
                        {% if request.user in project.members.all %}<p class="right leave-button" ><a href="{% url 'project-leave' project.slug %}" class="ajax btn btn-danger" data-replace=".leave-button"><i class="fa fa-times"></i> Leave project</a></p>{% endif %}
                        {% if not request.user in project.members.all %}<p class="right join-button" ><a href="{% url 'project-join' project.slug %}" class="ajax btn btn-success" data-replace=".join-button"><i class="fa fa-plus"></i> Join project</a></p>{% endif %}
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        <div class="member-box">
                        {% with project.members.all as members %}
                        {% include 'brigade/_member_list.html' %}
                        {% endwith %}
                        <br />
                    </div>
                        <br />
                        <hr />
                        <p>Public: <a href="{{object.public_url}}">{{object.public_url}}</a></p>
                        {% if project.dev_url %}
                        <p>Want to help? We use the following URL to manage development of this project</p>
                        <p><a href="{{project.dev_url}}" class="">{{object.dev_url}}</a></p>
                        {% endif %}
                        <hr />
                        {% if request.user.is_authenticated %}
                        {% if user.is_authenticated %}<a href="{% url 'project-update' project.slug %}" class="btn btn-primary ">Edit project</a>{% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3>Project buzz {% if user.is_authenticated %}<a href="{% url 'buzz-create' object.slug %}" class="btn btn-primary" class="" data-toggle="modal" data-target="#modal" >Add more buzz</a>{% endif %}</h3>
                        </div>
                        <div class="panel-body">
                            {% if project.buzz_set.all %}
                            {% for buzz in project.buzz_set.all %}
                            <h5>{{buzz.title}}</h5>
                            <div class="well">
                                {{buzz.description|markdown}}
                                <p class="byline">{{buzz.modified}} by <a href="{{buzz.author.get_absolute_url}}">{{buzz.author}}</a></p>
                            </div>
                            {% endfor %}
                            {% else %}
                            <p><i>There's no buzz about this project, find some fellow workers, and get busy!</i></p>
                            <p>{% if user.is_authenticated %}<a href="{% url 'buzz-create' object.slug %}" class="tiny button radius ">Add some buzz</a>{% endif %}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    </div>
  </div>
</div>


{% endblock %}

codeformaine/apps/brigade/templates/brigade/project_form.html
{% extends "dashboard_base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block extra_js %}
<script src="{% static 'bootstrap-multiselect/js/bootstrap-multiselect.js' %}" ></script>
<script src="{% static 'bootstrap-multiselect/js/prettify.js' %}" ></script>
<link href="{% static 'bootstrap-multiselect/css/bootstrap-multiselect.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap-multiselect/css/prettify.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}" ></script>
<link href="{% static 'bootstrap-colorpicker/css/colorpicker.css' %}" rel="stylesheet">
<script type="text/javascript">
$(document).ready(function() {
    jQuery('.multiselect').multiselect();
    jQuery('.colorpicker').colorpicker();
});
</script>
<script>
jQuery('document').ready(function() {
    jQuery("<a href='{% url 'topic-create' %}' data-toggle='modal' data-target='#modal' class='btn btn-primary'><i class='fa fa-plus'></i></a>").insertAfter('#id_topics');
    jQuery("<a href='{% url 'event-create' %}' data-toggle='modal' data-target='#modal' class='btn btn-primary'><i class='fa fa-plus'></i></a>").insertAfter('#id_events');
    jQuery("<a href='{% url 'technology-create' %}' data-toggle='modal' data-target='#modal' class='btn btn-primary'><i class='fa fa-plus'></i></a>").insertAfter('#id_technologies');
});
</script>
{% endblock %}

{% block header_title %}{% if not object %}Add{% else %}Edit{% endif %}{% endblock %}

{% block content %}
<div class="content-main">
    <div class="container">
        <div class="row project-card">
            <div class="small-12">
                <h2>{% if not object %}New {% else %}{{object}}{% endif %} project</h2>
                {% bootstrap_form_errors form %}
                <form method="post" action=".">{% csrf_token %}
                    {% bootstrap_form form %}
                    <p><input class="btn btn-success" type="submit" value="{% if not object %}Add{% else %}Save{% endif %}"></p>
                </form>
            </div>
        </div>
    </div>
</div>
        
<div id="modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    </div>
  </div>
</div>

<div id="myModal"></div>
{% endblock %}

codeformaine/apps/brigade/templates/brigade/projectidea_form.html
{% extends "dashboard_base.html" %}
{% load static %}
{% load bootstrap3 %}

{% block extra_js %}
<script src="{% static 'bootstrap-multiselect/js/bootstrap-multiselect.js' %}" ></script>
<script src="{% static 'bootstrap-multiselect/js/prettify.js' %}" ></script>
<link href="{% static 'bootstrap-multiselect/css/bootstrap-multiselect.css' %}" rel="stylesheet">
<link href="{% static 'bootstrap-multiselect/css/prettify.css' %}" rel="stylesheet">
<script src="{% static 'bootstrap-colorpicker/js/bootstrap-colorpicker.js' %}" ></script>
<link href="{% static 'bootstrap-colorpicker/css/colorpicker.css' %}" rel="stylesheet">
<script type="text/javascript">
$(document).ready(function() {
    jQuery('.multiselect').multiselect();
    jQuery('.colorpicker').colorpicker();
});
</script>
<script>
jQuery('document').ready(function() {
    jQuery("<a href='{% url 'topic-create' %}' data-toggle='modal' data-target='#modal' class='btn btn-primary'><i class='fa fa-plus'></i></a>").insertAfter('#id_topics');
    jQuery("<a href='{% url 'event-create' %}' data-toggle='modal' data-target='#modal' class='btn btn-primary'><i class='fa fa-plus'></i></a>").insertAfter('#id_events');
    jQuery("<a href='{% url 'technology-create' %}' data-toggle='modal' data-target='#modal' class='btn btn-primary'><i class='fa fa-plus'></i></a>").insertAfter('#id_technologies');
});
</script>
{% endblock %}

{% block header_title %}{% if not object %}Add{% else %}Edit{% endif %}{% endblock %}

{% block content %}
<div class="content-main">
    <div class="container">
        <div class="row project-card">
            <div class="small-12">
                <h2>{% if not object %}New {% else %}{{object}}{% endif %} project idea</h2>
                {% bootstrap_form_errors form %}
                <form method="post" action=".">{% csrf_token %}
                    {% bootstrap_form form %}
                    <p><input class="btn btn-success" type="submit" value="{% if not object %}Add{% else %}Save{% endif %}"></p>
                </form>
            </div>
        </div>
    </div>
</div>
        
<div id="modal" class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
    </div>
  </div>
</div>

<div id="myModal"></div>
{% endblock %}